ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'GENERAL_MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'PRODUCTION_MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'HEAD_OF_OPERATIONS';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPERVISOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ACCOUNTANT';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'LOGISTICS_TEAM';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'DESIGN_TEAM';
