ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'HUMAN_RESOURCES';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CUSTOMER_CARE';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FACTORY_WORKER';

ALTER TABLE "User"
ADD COLUMN "jobTitle" TEXT,
ADD COLUMN "department" TEXT,
ADD COLUMN "phoneNumber" TEXT,
ADD COLUMN "reportingLine" TEXT;